### ISSUE TITLE
Recently/Most Played Tab

### ISSUE THREAD

**Issue by moebrowne** [freshleafmedia/jukebox#27]
It would be nice to have the song selection modal have a tab for search as we do now but then also a tab with a list of the last or most played 25 songs

**Comment by joestrong** [comment]
Most played is now in place.

@moebrowne do we feel we need a recently played? It would probably be useful if it was split by user

**Comment by moebrowne** [comment]
@joestrong Maybe it can be apart of the statistics tab (#22) instead
