### ISSUE TITLE
Channels Returned In Results

### ISSUE THREAD

**Issue by moebrowne** [freshleafmedia/jukebox#29]
When YT channels are returned in results it causes the search to not display results.

Believe this is to do with trying the get song durations?

**Comment by moebrowne** [comment]
@joestrong did you say there was still something to fix on this?

**Comment by joestrong** [comment]
@moebrowne I fixed the bug on develop [here](https://github.com/freshleafmedia/jukebox/commit/568862628931e60a6e70a34d7d69cde67aa580fa#diff-99dc905ad73e9472b87b27c4b45db4f5R107) (Filter method that only allows videos, no channels/playlists/etc)
