### ISSUE TITLE
Search Debounce

### ISSUE THREAD

**Issue by moebrowne** [freshleafmedia/jukebox#30]
It would be good to wait for the user to stop typing for a short period before firing the API search event as they get queued up and when typing you fire a fair few requests.

There must be an API limit but i guess we are no where near it?

**Comment by joestrong** [comment]
I've added a debounce in b2ec059aedb0b281d5bbc6a9b844fad2b5c800b8

**Comment by moebrowne** [comment]
@joestrong Nice one!
