### ISSUE TITLE
Crashing....

### ISSUE THREAD

**Issue by moebrowne** [freshleafmedia/jukebox#35]
Every now and again the whole thing just crashes it seems to be just as a song ends:

``` node
SONG[xN99hTB6rLU] STATE: playing_finished
SONG[xN99hTB6rLU] STATE: removing
PLAYLIST[0] STATE: ready
fs.js:980
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'playlists/0.json'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:980:18)
    at Playlist.<anonymous> (/var/www/html/server/playlist.js:93:8)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

This leaves the `0.json` play list completely empty

**Comment by joestrong** [comment]
@moebrowne The unlink code is there to remove the playlist file before writing it again, right? I would guess that another song status update triggers another unlink before the previous write has had time to finish.

Perhaps we can try making the write synchronous?

**Comment by moebrowne** [comment]
Seems to be fixed..
