### ISSUE TITLE
Dockerise

### ISSUE THREAD

**Issue by freshleafmedia** [freshleafmedia/jukebox#38]
Add a Dockerfile to make development easier

**Comment by joestrong** [comment]
The main docker problems is sound. Everything else works.

A lot of people suggest setting up a pulseaudio server and having the docker container connect to that, but I feel like there should be a simple way for this to work without host-machine configuration.

**Comment by moebrowne** [comment]
@joestrong I couldn't get them to work but there maybe something to these:
- http://stackoverflow.com/questions/28985714/run-apps-using-audio-in-a-docker-container
- https://hub.docker.com/r/chrisdaish/vlc/
- https://www.len.ro/work/running-chrome-in-docker-with-audio/
- https://hub.docker.com/r/sassmann/ubuntu-steam/

**Comment by joestrong** [comment]
@moebrowne I think the docker sound branch can be merged. Seems fine to me :+1:

**Comment by moebrowne** [comment]
This is now fixed in develop
